### ISSUE TITLE
L4D2 Support?

### ISSUE THREAD

**Issue by CanadianJeff** [J-Tanzanite/Lilac-SourceTV#2]
I have attempted to see if these server commands are in the Left 4 Dead 2 game and they are not

**Comment by J-Tanzanite** [comment]
By server commands, I assume you mean ConVars.
Try editing the file in "cfg/sourcemod/lilac_sourcetv.cfg"

If the file doesn't exist, then I would guess the plugin isn't loading correctly, type "sm plugins list" and show me the output.

**Comment by J-Tanzanite** [comment]
Due to lack of replies, I'm going to close this.
If you have something to add or any updates, feel free to re-open this issue :)
