### ISSUE TITLE
Doubt with demo recording system

### ISSUE THREAD

**Issue by crashzk** [J-Tanzanite/Lilac-SourceTV#4]
GOTV config of my server is as follows:
```
//GOTV
tv_enable "1"
tv_autorecord "1"
tv_delay "12"
tv_advertise_watchable "1"
tv_maxclients "5"
tv_title "[ ZK Servidores™ ] GOTV" 
tv_name "[ ZK Servidores™ ] GOTV"
tv_password ""
tv_allow_camera_man "1"
tv_allow_static_shots "1"
tv_snapshotrate "32"
tv_nochat "0" 
tv_timeout "45"
//tv_port "27015"
tv_delaymapchange "0"
tv_dispatchmode "1"
tv_relayvoice "1"
tv_transmitall "1"
```
I'm using both **Anti-Cheat Lilac** and **Lilac-SourceTV**.

What problem I'm facing, server only records the demos that **Lilac-SourceTV** creates, when a player is banned only records the demo of that moment and such.

I would like the server to record all demos, all maps, even if players are not banned by AC. And when any player is banned by AC the plugin still records an exclusive demo of it as proof.

Would something like this be possible?

**Comment by J-Tanzanite** [comment]
I don't think that would be possible, sadly.
As far as I know, STV can only record one demo at the time.
This means that you really can't have a single demo of an entire match and a single demo of someone who cheated in it at the same time.

At best, you could edit the source code so that it splits the demo up...
IE, stop and start demos...
Tho I don't think that would be terribly useful.

---

Perhaps a log-only option would be useful? So that you have single demos of all matches, but a log telling you if a cheater was in a demo and for how long?
That might be useful? :)

**Comment by crashzk** [comment]
It would be perfect to show the cheater and the time in the log.

Is that before I used SQLMatches, even with the AC and the Plugin to record the demo when I had cheated the demos still saved on the SQLMatches website and complete and still had the demo if someone was banned by the AC.

Anyway, I believe that a log with the cheater information and the complete demo would be perfect for me now.

**Comment by crashzk** [comment]
Doubt @J-Tanzanite, configuring the plugin like this:
```
// Automatically restart map if SourceTV bot hasn't joined.
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
lilac_stv_autojoin "1"

// Enable SourceTV auto recording.
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
lilac_stv_enable "0"

// Log recording info to addons/sourcemod/logs/lilac_stv.log
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
lilac_stv_log "1"

// Automatically set SourceTV demo tickrate to the highest value possible for best quality recordings.
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
lilac_stv_tickrate "1"
```
Would it work already? It would record the data in the LOG, but not the demo.

**Comment by J-Tanzanite** [comment]
I have to apologize for my incredibly slow reply, been busy as of late.

That said, no, in the current version of Lilac SourceTV, it can't only log. I have to add that as a feature.
I'll make a version later (today hopefully) which will add another ConVar that lets you log-only :)

**Comment by J-Tanzanite** [comment]
I wrote this code in a hurry: https://github.com/J-Tanzanite/Lilac-SourceTV/tree/development

It's **NOT** tested, and may not work...
But just set `lilac_stv_record` to `0`, and it should in theory work.
`lilac_stv_log` must remain `1`.

---
Edit: If it doesn't work, I'll take a look at it either tomorrow or in some days... Sorry for the delays

**Comment by crashzk** [comment]
Thanks, I will test here and return with feedback.

For now thank you.

**Comment by crashzk** [comment]
@J-Tanzanite today a player was banned by AC, recorded in AC log.
```
17/10/2021 | 12:02:39 [Version 1.7.1] {Name: "i don't miss" | SteamID: STEAM_1:0:627388164 | IP: XX9.9X.XX.X7} was detected and banned for Anti-Duck-Delay.
```
https://sourcebans.zkservidores.com/index.php?p=banlist&advSearch=STEAM_1:0:627388164&advType=steamid&Submit

But it didn't create the Lilac-SourceTV log and didn't record anything.

Configuration I'm using:
```
// Automatically restart map if SourceTV bot hasn't joined.
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
lilac_stv_autojoin "1"

// Enable this plugin.
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
lilac_stv_enable "1"

// Log recording info to addons/sourcemod/logs/lilac_stv.log
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
lilac_stv_log "1"

// Automatically record demos (Disable this if you want to log-only).
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
lilac_stv_record "0"

// Automatically set SourceTV demo tickrate to the highest value possible for best quality recordings.
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
lilac_stv_tickrate "1"
```
**[Lilac] Little Anti-Cheat (1.7.1) by J_Tanzanite
[Lilac] Auto SourceTV Recorder (1.2.0) by J_Tanzanite**

**Comment by J-Tanzanite** [comment]
I wouldn't worry about it, as Lilac SourceTV is not supposed to record or log on Anti-Duck-Delay.

> ```
> 17/10/2021 | 12:02:39 [Version 1.7.1] {Name: "i don't miss" | SteamID: STEAM_1:0:627388164 | IP: XX9.9X.XX.X7} was detected and banned for Anti-Duck-Delay.
> ```

Lilac SourceTV will only listen for Aimbot, not other features.

---

> But it didn't create the Lilac-SourceTV log and didn't record anything.

Like you showed me earlier, you record all matches with `tv_autorecord 1`, and with `lilac_stv_record 0` Lilac SourceTV won't start another demo (as doing so would mess with your already ongoing recording).
So it should only log, but not in this case, as it won't record Anti-Duck-Delay.

> Configuration I'm using:
> 
> ```
> // Automatically restart map if SourceTV bot hasn't joined.
> // -
> // Default: "1"
> // Minimum: "0.000000"
> // Maximum: "1.000000"
> lilac_stv_autojoin "1"
> 
> // Enable this plugin.
> // -
> // Default: "1"
> // Minimum: "0.000000"
> // Maximum: "1.000000"
> lilac_stv_enable "1"
> 
> // Log recording info to addons/sourcemod/logs/lilac_stv.log
> // -
> // Default: "1"
> // Minimum: "0.000000"
> // Maximum: "1.000000"
> lilac_stv_log "1"
> 
> // Automatically record demos (Disable this if you want to log-only).
> // -
> // Default: "1"
> // Minimum: "0.000000"
> // Maximum: "1.000000"
> lilac_stv_record "0"
> 
> // Automatically set SourceTV demo tickrate to the highest value possible for best quality recordings.
> // -
> // Default: "1"
> // Minimum: "0.000000"
> // Maximum: "1.000000"
> lilac_stv_tickrate "1"
> ```
> 
> **[Lilac] Little Anti-Cheat (1.7.1) by J_Tanzanite
[Lilac] Auto SourceTV Recorder (1.2.0) by J_Tanzanite**

Also, your config file is good :)
You just need to wait for an Aimbot ban to occur.

**Comment by crashzk** [comment]
Worked, thank you. I believe it can be merged into the **`master`** branch.
