### ISSUE TITLE
Save full demo automatically

### ISSUE THREAD

**Issue by crashzk** [J-Tanzanite/Lilac-SourceTV#5]
I have the following configuration:
```
// This file was auto-generated by SourceMod (v1.10.0.6513)
// ConVars for plugin "lilac_sourcetv.smx"


// Automatically restart map if SourceTV bot hasn't joined.
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
lilac_stv_autojoin "1"

// Enable this plugin.
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
lilac_stv_enable "1"

// Log recording info to addons/sourcemod/logs/lilac_stv.log
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
lilac_stv_log "1"

// Automatically record demos (Disable this if you want to log-only).
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
lilac_stv_record "0"

// Automatically set SourceTV demo tickrate to the highest value possible for best quality recordings.
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
lilac_stv_tickrate "1"
```
In this case I would like to leave it disabled for when a player is banned by AC to record the demo and let it record the demo of the entire map, using the command `tv_autorecord "1"`.

But even with the current configuration, whenever I try to activate the `tv_autorecord` function, **Lilac SourceTV** blocks the change.

![image](https://user-images.githubusercontent.com/32937653/147497510-bd68403b-6c9e-4aa6-9c8a-e4d62fdec7d0.png)

In the same case not creating an automatic demo when a player is banned I would like to create the log to register, but it does not work with the config above.

Any mistake on my part? Or the feature is not working even just logging.

**Comment by J-Tanzanite** [comment]
Sorry for the slow reply.

No, the mistake is not on your part, it's on mine.
I simply forgot to add a line of code to prevent blocking of `tv_autorecord` if `lilac_stv_record` is set to 0.

I haven't tested this [change](https://github.com/J-Tanzanite/Lilac-SourceTV/commit/1923e0d79b53d56daab020f22d6e4f4223eecc9d), but it should work now.
Give it a try.

Also, you might want to add `tv_autorecord 1` to the bottom of the `lilac_sourcetv.cfg` file.
Otherwise, it may not work.

**Comment by crashzk** [comment]
Thanks, I will be testing and return with the results.

**Comment by crashzk** [comment]
**@J-Tanzanite** Sorry for the delay, I tested it with this version you sent, working perfectly so far.

I believe it can be merged into the branch **master**.
